export const API_CALL = 'API_CALL';

export const GET_ENTERPRISE_DETAILS = {
  START: 'GET_ENTERPRISE_DETAILS_START',
  SUCCESS: 'GET_ENTERPRISE_DETAILS_SUCCESS',
  FAIL: 'GET_ENTERPRISE_DETAILS_FAIL',
};

export const GET_MOBILE_NUMBER = {
  START: 'GET_MOBILE_NUMBER_START',
  SUCCESS: 'GET_MOBILE_NUMBER_SUCCESS',
  FAIL: 'GET_MOBILE_NUMBER_FAIL',
};

export const GET_ENTER_OTP = {
  START: 'GET_ENTER_OTP_START',
  SUCCESS: 'GET_ENTER_OTP_SUCCESS',
  FAIL: 'GET_ENTER_OTP_FAIL',
};

export const GET_PASSCODE = {
  START: 'GET_PASSCODE_START',
  SUCCESS: 'GET_PASSCODE_SUCCESS',
  FAIL: 'GET_PASSCODE_FAIL',
};

export const GET_PASSCODE_LOGIN = {
  START: 'GET_PASSCODE_LOGIN_START',
  SUCCESS: 'GET_PASSCODE_LOGIN_SUCCESS',
  FAIL: 'GET_PASSCODE_LOGIN_FAIL',
};

export const GET_ENTERPRISE_DETAILS_LOGIN = {
  START: 'GET_ENTERPRISE_DETAILS__LOGIN_START',
  SUCCESS: 'GET_ENTERPRISE_DETAILS__LOGIN_SUCCESS',
  FAIL: 'GET_ENTERPRISE_DETAILS__LOGIN_FAIL',
};

// export const GET_UNAUTHORIZATION_ERROR = {
//   START: 'GET_UNAUTHORIZATION_ERROR_START',
//   SUCCESS: 'GET_UNAUTHORIZATION_ERROR_SUCCESS',
//   FAIL: 'GET_UNAUTHORIZATION_ERROR_FAIL',
// };
